#!/usr/bin/env bash
# controls/1.1.1.10_unused_filesystems_kernel_modules_are_not_available.sh

execute_control() {
    local CONTROL_ID="1.1.1.10"
    local TITLE="Ensure unused filesystems kernel modules are not available ((Manual)"
    local EXPECTED="Verify filesystem kernel modules that are not in use on the system are disabled. Review
currently loaded kernel modules to ensure they are needed and conform to local site
policy.
Note: The \"Audit script\" included at the bottom of the \"Audit Procedure\" will perform the
steps included below.
1. Run the following command to generate a list of filesystem types currently
mounted on the system.
# findmnt -Dkerno fstype | sort -u
Review the output. These filesystem types should either be excluded from the audit or if
no longer needed, unmounted and disabled.
Example output:
devtmpfs
ext4
tmpfs
vfat
2. Run the following script to generate a list of all file system kernel modules
currently installed on the system:
#!/usr/bin/env bash
{
l_search=\"\$(readlink -e /usr/lib/modules/ || readlink -e /lib/modules/)\"
a_module=()
while IFS= read -r -d \$'\0' l_module_dir; do
if [ ! \"\$(basename \"\$l_module_dir\")\" = \"nls\" ]; then
while IFS= read -r -d \$'\0' l_module_file; do
l_mname=\"\$(basename \"\$l_module_file\" | cut -d'.' -f1)\"
if [ -f \"\$l_module_file\" ] && ! grep -Psiq -- '\b'\"\$l_mname\"'\b'
\
<<< \"\${a_module[*]}\"; then
a_module+=(\"\$l_mname\")
fi
done < <(find -L \"\$l_module_dir\" -mindepth 1 -maxdepth 1 -type f print0)
fi
done < <(find \"\$l_search\"/**/kernel/fs/ -mindepth 1 -maxdepth 1 -type d !
-empty -print0)
printf '%s\n' \"\" \"\${a_module[@]}\"
}
The output is a list of the kernel modules included in the
/usr/lib/modules/{KERNEL_VERSION}/kernel/fs/ or
/lib/modules/{KERNEL_VERSION}/kernel/fs/ directories. This list has been sorted
to be unique values, ignore items in the nls directory, and added to an array called
a_module.
3. Run the following command to generate a list of modules currently loaded into
the kernel:
# lsmod
4. compare the output from the list generated in step 2 to the list of loaded modules
generated by the lsmod command in step 3. Any module appearing in both lists
is currently loaded into the kernel. Review these to verify they are needed and
approved by local site policy
5. Run the following command to generate a list of modules that are set to be Deny
Listed: blacklist {MODULE_NAME}, and/or set be be not loadable: install
{MODULE_NAME} /bin/false or install {MODULE_NAME} /bin/true:
# modprobe --showconfig | grep -Pi -- '^\h*(blacklist|install)\h+'
6. Verify all modules in the output from the list generated in step 2 are both Deny
Listed: blacklist {MODULE_NAME} and set to be not loadable: install
{MODULE_NAME} /bin/false or install {MODULE_NAME} /bin/true.
Audit Script:
#!/usr/bin/env bash
{
a_check=() a_output=() a_module=() a_output2=() a_output3=()
l_search=\"\$(readlink -e /usr/lib/modules/ || readlink -e /lib/modules/)\"
IFS=\$'\n' read -r -d '' -a a_mounted < <(findmnt -Dkerno fstype \
| sort -u && printf '\0' )
IFS=\$'\n' read -r -d '' -a a_lsmod < <(lsmod | awk '{print \$1}' && printf
'\0' )
IFS=\$'\n' read -r -d '' -a a_showconfig < <(modprobe --showconfig | \
grep -Pi -- '^\h*(blacklist|install)\h+' && printf '\0')
while IFS= read -r -d \$'\0' l_module_dir; do
if [ ! \"\$(basename \"\$l_module_dir\")\" = \"nls\" ]; then
while IFS= read -r -d \$'\0' l_module_file; do
l_mname=\"\$(basename \"\$l_module_file\" | cut -d'.' -f1)\"
if [ -f \"\$l_module_file\" ] && ! grep -Psiq -- '\b'\"\$l_mname\"'\b'
<<< \"\${a_module[*]}\"; then
a_module+=(\"\$l_mname\")
fi
done < <(find -L \"\$l_module_dir\" -mindepth 1 -maxdepth 1 -type f print0)
fi
done < <(find \"\$l_search\"/**/kernel/fs/ -mindepth 1 -maxdepth 1 -type d !
-empty -print0)
for l_module in \"\${a_module[@]}\"; do
if grep -Psoiq -- '\b'\"\$l_module\"'\b' <<< \"\${a_mounted[*]}\"; then
a_output+=(\" - \\\"\$l_module\\\"\")
elif grep -Psoiq -- '\b'\"\$l_module\"'\b' <<< \"\${a_lsmod[*]}\"; then
a_output2+=(\" - \\\"\$l_module\\\"\")
elif ! grep -Psioq -- '\binstall\h+'\"\${l_module//-/_}\"'\h+\H+\b' <<<
\"\${a_showconfig[*]}\" || \
! grep -Psioq -- '\bblacklist\h+'\"\${l_module//-/_}\"'\b' <<<
\"\${a_showconfig[*]}\"; then
a_output3+=(\" - \\\"\$l_module\\\"\")
fi
done
[ \"\${#a_output[@]}\" -gt 0 ] && printf '%s\n' \"\" \
\"- There are \\\"\${#a_output[@]}\\\" kernel modules currently mounted:\"
\"\${a_output[@]}\"
[ \"\${#a_output2[@]}\" -gt 0 ] && printf '%s\n' \"\" \
\"- There are \\\"\${#a_output2[@]}\\\" kernel modules currently loaded:\"
\"\${a_output2[@]}\"
[ \"\${#a_output3[@]}\" -gt 0 ] && printf '%s\n' \"\" \
\"- There are \\\"\${#a_output3[@]}\\\" Kernel modules currently loadable:\"
\"\${a_output3[@]}\"
}
WARNING: disabling or denylisting filesystem modules that are in use on the system
may be FATAL. It is extremely important to thoroughly review this list."
    local RISK="Unknown"
    local DESC="Filesystem kernel modules are pieces of code that can be dynamically loaded into the
Linux kernel to extend its filesystem capabilities, or so-called base kernel, of an
operating system. Filesystem kernel modules are typically used to add support for new
hardware (as device drivers), or for adding system calls.

Rationale:
While loadable filesystem kernel modules are a convenient method of modifying the
running kernel, this can be abused by attackers on a compromised system to prevent
detection of their processes or files, allowing them to maintain control over the system.
Many rootkits make use of loadable filesystem kernel modules in this way.
Removing support for unneeded filesystem types reduces the local attack surface of the
system. If this filesystem type is not needed, disable it. The following filesystem kernel
modules have known CVE's and should be made unavailable if no dependencies exist:
•
•
•
•
•
•
•
•
•
•
•
ceph - CVE-2022-0670
cifs - CVE-2022-29869
exfat CVE-2022-29973
ext CVE-2022-1184
fat CVE-2022-22043
fscache CVE-2022-3630
fuse CVE-2023-0386
gfs2 CVE-2023-3212
nfs_common CVE-2023-6660
nfsd CVE-2022-43945
smbfs_common CVE-2022-2585"
    local ATTACK="This list may be quite extensive and covering all edges cases is difficult. Therefore, it's
crucial to carefully consider the implications and dependencies before making any
changes to the filesystem kernel module configurations."
    local REMEDIATION="- IF - the module is available in the running kernel:
•
•
•
Unload the filesystem kernel module from the kernel
Create a file ending in .conf with install filesystem kernel modules /bin/false
in the /etc/modprobe.d/ directory
Create a file ending in .conf with deny list filesystem kernel modules in the
/etc/modprobe.d/ directory
WARNING: unloading, disabling or denylisting filesystem modules that are in use on the
system may be FATAL. It is extremely important to thoroughly review the filesystems
returned by the audit before following the remediation procedure.
Example of unloading the gfs2kernel module:
modprobe -r gfs2 2>/dev/null
rmmod gfs2 2>/dev/null
Example of fully disabling the gfs2 kernel module:
printf '%s\n' \"\" \"blacklist gfs2\" \"install gfs2 /bin/false\" >>
/etc/modprobe.d/gfs2.conf
Note:
•
•
Disable a kernel module by modifying the command above for each unused
filesystem kernel module
The example gfs2 must be updated with the appropriate module name for the
command or example script bellow to run correctly.
Below is an example script that can be modified to use on various filesystem
kernel modules manual remediation process:
Example Script
#!/usr/bin/env bash
{
a_output2=(); a_output3=(); l_dl=\"\" # Initialize arrays and clear
variables
l_mod_name=\"gfs2\" # set module name
l_mod_type=\"fs\" # set module type
l_mod_path=\"\$(readlink -f /usr/lib/modules/**/kernel/\$l_mod_type ||
readlink -f /lib/modules/**/kernel/\$l_mod_type)\"
f_module_fix()
{
l_dl=\"y\" # Set to ignore duplicate checks
a_showconfig=() # Create array with modprobe output
while IFS= read -r l_showconfig; do
a_showconfig+=(\"\$l_showconfig\")
done < <(modprobe --showconfig | grep -P -'\b(install|blacklist)\h+'\"\${l_mod_name//-/_}\"'\b')
if lsmod | grep \"\$l_mod_name\" &> /dev/null; then # Check if the module
is currently loaded
a_output2+=(\" - unloading kernel module: \\\"\$l_mod_name\\\"\")
modprobe -r \"\$l_mod_name\" 2>/dev/null; rmmod \"\$l_mod_name\"
2>/dev/null
fi
if ! grep -Pq -- '\binstall\h+'\"\${l_mod_name///_}\"'\h+(\/usr)?\/bin\/(true|false)\b' <<< \"\${a_showconfig[*]}\"; then
a_output2+=(\" - setting kernel module: \\\"\$l_mod_name\\\" to
\\\"\$(readlink -f /bin/false)\\\"\")
printf '%s\n' \"install \$l_mod_name \$(readlink -f /bin/false)\" >>
/etc/modprobe.d/\"\$l_mod_name\".conf
fi
if ! grep -Pq -- '\bblacklist\h+'\"\${l_mod_name//-/_}\"'\b' <<<
\"\${a_showconfig[*]}\"; then
a_output2+=(\" - denylisting kernel module: \\\"\$l_mod_name\\\"\")
printf '%s\n' \"blacklist \$l_mod_name\" >>
/etc/modprobe.d/\"\$l_mod_name\".conf
fi
}
for l_mod_base_directory in \$l_mod_path; do # Check if the module exists
on the system
if [ -d \"\$l_mod_base_directory/\${l_mod_name/-/\/}\" ] && [ -n \"\$(ls -A
\"\$l_mod_base_directory/\${l_mod_name/-/\/}\")\" ]; then
a_output3+=(\" - \\\"\$l_mod_base_directory\\\"\")
[[ \"\$l_mod_name\" =~ overlay ]] && l_mod_name=\"\${l_mod_name::-2}\"
[ \"\$l_dl\" != \"y\" ] && f_module_fix
else
echo -e \" - kernel module: \\\"\$l_mod_name\\\" doesn't exist in
\\\"\$l_mod_base_directory\\\"\"
fi
done
[ \"\${#a_output3[@]}\" -gt 0 ] && printf '%s\n' \"\" \" -- INFO --\" \" - module:
\\\"\$l_mod_name\\\" exists in:\" \"\${a_output3[@]}\"
[ \"\${#a_output2[@]}\" -gt 0 ] && printf '%s\n' \"\" \"\${a_output2[@]}\" ||
printf '%s\n' \"\" \" - No changes needed\"
printf '%s\n' \"\" \" - remediation of kernel module: \\\"\$l_mod_name\\\"
complete\" \"\"
}"

    local RESULT="FAIL"
    local CURRENT="Manual audit required. Please verify against the expected configuration."

    # NOTE: This is an auto-generated stub.
    # Add real bash logic to evaluate compliance status.

    save_result "$CONTROL_ID" "$TITLE" "$EXPECTED" "$CURRENT" "$RESULT" "$RISK" "$REMEDIATION" "$DESC" "$ATTACK"
}
