#!/usr/bin/env bash
# controls/6.1.1.1.3_journald_log_file_rotation_is_configured.sh

execute_control() {
    local CONTROL_ID="6.1.1.1.3"
    local TITLE="Ensure journald log file rotation is configured ((Manual)"
    local EXPECTED="Review /etc/systemd/journald.conf and files in the
/etc/systemd/journald.conf.d/ directory ending in .conf. Verify logs are rotated
according to site policy.
Run the following command and ensure logs are rotated according to site policy:
# systemd-analyze cat-config systemd/journald.conf | tac | \
grep -Psi -'\b(SystemMaxUse|SystemKeepFree|RuntimeMaxUse|RuntimeKeepFree|MaxFileSec)='
SystemMaxUse=
SystemKeepFree=
RuntimeMaxUse=
RuntimeKeepFree=
MaxFileSec="
    local RISK="Unknown"
    local DESC="Journald includes the capability of rotating log files regularly to avoid filling up the
system with logs or making the logs unmanageably large. The file
/etc/systemd/journald.conf is the configuration file used to specify how logs
generated by Journald should be rotated.

Rationale:
By keeping the log files smaller and more manageable, a system administrator can
easily archive these files to another system and spend less time looking through
inordinately large log files."
    local ATTACK=""
    local REMEDIATION="Edit /etc/systemd/journald.conf or a file ending in .conf the
/etc/systemd/journald.conf.d/ directory. Set the following parameters in the
[Journal] section to ensure logs are rotated according to site policy. The settings
should be carefully understood as there are specific edge cases and prioritization of
parameters.
Example Configuration
[Journal]
SystemMaxUse=1G
SystemKeepFree=500M
RuntimeMaxUse=200M
RuntimeKeepFree=50M
MaxFileSec=1month
Note: If these settings appear in a canonically later file, or later in the same file, the
setting will be overwritten"

    local RESULT="FAIL"
    local CURRENT="Manual audit required. Please verify against the expected configuration."

    # NOTE: This is an auto-generated stub.
    # Add real bash logic to evaluate compliance status.

    save_result "$CONTROL_ID" "$TITLE" "$EXPECTED" "$CURRENT" "$RESULT" "$RISK" "$REMEDIATION" "$DESC" "$ATTACK"
}
